.TH PY\-UNIX\-CMD 1 2015 py-unix-cmd "Python Unix Command"
.SH NAME
py\-unix\-cmd \- example of a Unix command written in Python
.SH SYNOPSIS
.B py\-unix\-cmd
[options]
.SH DESCRIPTION
This program serves as an example of how a Unix command can be written in the
Python programming language.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
print usage information and then exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR
include information useful for debugging
.SH EXIT STATUS
The exit status is 0 on normal termination, and 1 on error.
.SH DIAGNOSTICS
Errors will print a message to the standard error stream. To enable stack
traces for debugging, enable the \*(lqverbose\*(rq option.
.SH EXAMPLES
Examples...
.SH SEE ALSO
See also...
.SH BUGS
Any known bugs...
.SH AUTHOR
Whoever made this...
